name: RedHopperFiller
version: '${minecraft.plugin.version}'
main: de.redstoneworld.redhopperfiller.RedHopperFiller
authors: [Phoenix616]
commands:
   redhopperfiller:
      aliases: [hopperfiller,hf]
      description: Command description.
      usage: /<command> [<strength>|reload]
      permission: rwm.hopperfiller.use
      permission-message: You don't have the permission <permission>
permissions:
   rwm.hopperfiller.use:
      description: Gives permission to the plugin command
      default: op
   rwm.hopperfiller.reload:
      description: Gives permission to the plugin command
      default: op
   rwm.hopperfiller.setstrength:
      description: Gives permission to set the strength in the command
      default: op